### ISSUE TITLE
Tests are not working issue with driver

### ISSUE THREAD

**Issue by lachowsa** [dalenguyen/WebdriverIO-TypeScript-Boilerplate#10]
Hi,

there is an issue with running the test, here is the log after npm install + npm run test:

adrianlachowski@MacBook-Pro-Adrian WebdriverIO-TypeScript-Boilerplate % npm run test

> webdriverio-typescript-boilerplate@1.0.1 test /Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate
> rimraf reports/* && npm run report:history && npm run prettier && wdio

> webdriverio-typescript-boilerplate@1.0.1 report:history /Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate
> mkdir -p allure-report/history allure-results/history && cp -a allure-report/history allure-results/

> webdriverio-typescript-boilerplate@1.0.1 prettier /Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate
> prettier --write --loglevel warn "**/**/*.ts"

2021-01-06T14:15:18.875Z DEBUG @wdio/sync: Couldn't load fibers package for Node v10 and above
2021-01-06T14:15:18.881Z DEBUG @wdio/sync: Couldn't load fibers package for Node v8

Execution of 3 spec files started at 2021-01-06T14:15:19.236Z

[0-0] RUNNING in chrome - /test/accessibility.spec.ts
[0-1] RUNNING in chrome - /test/example.spec.ts
[0-2] RUNNING in chrome - /test/test.page.spec.ts
[0-0] 2021-01-06T14:15:21.052Z ERROR webdriver: Request failed due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
[0-0] 2021-01-06T14:15:21.054Z ERROR @wdio/runner: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
[0-1] 2021-01-06T14:15:21.052Z ERROR webdriver: Request failed due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
2021-01-06T14:15:21.054Z ERROR @wdio/runner: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
2021-01-06T14:15:21.055Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0-2] 2021-01-06T14:15:21.053Z ERROR webdriver: Request failed due to session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
2021-01-06T14:15:21.054Z ERROR @wdio/runner: session not created: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'
Driver info: driver.version: unknown
    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:321:20)
    at Request.EventEmitter.emit (domain.js:485:12)
    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:427:28)
2021-01-06T14:15:21.055Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
0-0 worker error {
  name: 'session not created',
  message: 'Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown',
  stack: 'session not created: Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown\n' +
    '    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)\n' +
    '    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)\n' +
    '    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)\n' +
    '    at Object.onceWrapper (events.js:427:28)'
}
0-1 worker error {
  name: 'session not created',
  message: 'Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown',
  stack: 'session not created: Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown\n' +
    '    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)\n' +
    '    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)\n' +
    '    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)\n' +
    '    at Object.onceWrapper (events.js:427:28)'
}
[0-0] 2021-01-06T14:15:21.055Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
0-2 worker error {
  name: 'session not created',
  message: 'Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown',
  stack: 'session not created: Unable to create new service: ChromeDriverService\n' +
    "Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'\n" +
    "System info: host: 'MacBook-Pro-Adrian.local', ip: '192.168.0.220', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_172'\n" +
    'Driver info: driver.version: unknown\n' +
    '    at getErrorFromResponseBody (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/utils.js:175:10)\n' +
    '    at Request._callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/webdriver/build/request.js:110:64)\n' +
    '    at Request.self.callback (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:185:22)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at Request.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1161:10)\n' +
    '    at Request.emit (events.js:321:20)\n' +
    '    at Request.EventEmitter.emit (domain.js:485:12)\n' +
    '    at IncomingMessage.<anonymous> (/Users/adrianlachowski/WebstormProjects/WebdriverIO-TypeScript-Boilerplate/node_modules/request/request.js:1083:12)\n' +
    '    at Object.onceWrapper (events.js:427:28)'
}
[0-0] FAILED in chrome - /test/accessibility.spec.ts
[0-1] FAILED in chrome - /test/example.spec.ts
[0-2] FAILED in chrome - /test/test.page.spec.ts

Spec Files:      0 passed, 3 failed, 3 total (100% completed) in 00:00:01 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdriverio-typescript-boilerplate@1.0.1 test: `rimraf reports/* && npm run report:history && npm run prettier && wdio`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webdriverio-typescript-boilerplate@1.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adrianlachowski/.npm/_logs/2021-01-06T14_15_21_338Z-debug.log

**Comment by lachowsa** [comment]
I had some local issue, after my machine restart it started to work correctly
